### PR TITLE
Output directory should not be in source dir.

### LINKED ISSUE #15: Unusual target location
Follow the common cmake build steps, `mkdir build; cd build; cmake ..; make`, the below out libraries and binaries are not located under `build`,  instead located at src directory.
```
sdk/bin/debug/*
sdk/bin/release/*
sdk/lib/debug/*
sdk/lib/release/*
samples/bin/debug/*
samples/bin/release/*
tests/bin/*
```

There are two issues I file this issues:
*  Code tree is dirty (although ,gitignore hide them). One of benefit Cmake vs Makefile is code and build directory are de-coupled. Which make developer to re-use one code tree with multiple configurations. 
* CMake users normally suppose all generated files(Makefile, etc), libraries and binaries are located under build dir,

### PR DESCRIPTION
**Pull request by halton**
Fixes #15

### CODE REVIEW

**Comment by halton** [comment]
@EldarZ PTAL.

**Comment by halton** [comment]
@EldarZ any update?

**Comment by EldarZ** [comment]
Hi @halton, Thanks for the contributing! 
1. I'm checking regarding CLA before merging this.
2. We prefer binaries in a dedicated directory (bin, lib) under the build directory, Is there any justification to leave the binaries scattered in the build directory?

**Comment by halton** [comment]
@EldarZ as I describe in #15, There are two issues I file this issues:

* Code tree is dirty (although ,gitignore hide them). One of benefit Cmake vs Makefile is code and build directory are de-coupled. Which make developer to re-use one code tree with multiple configurations.
* CMake users normally suppose all generated files(Makefile, etc), libraries and binaries are located under build dir

Making  binaries in a dedicated directory (bin, lib) under the build directory should be okay, but it is not so common, because make install will install the targets as it now.

**Comment by EldarZ** [comment]
No CLA required.
Thanks @halton.

**Pull request merged**
